language: node_js
node_js:
  - "7.3"
after_success:
    - 'git config --global user.email travis'
    - 'git config --global user.name travis'
    - 'npm run coverage'
    - 'npm run build'
    - 'git config --local -l'
    - 'npm run deploy'
